# Generated by Django 4.1.2 on 2022-10-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance_System.student'),
        ),
    ]
