# Generated by Django 4.1.2 on 2022-10-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0002_class_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='class_student', to='Attendance_System.student'),
        ),
    ]
