# Generated by Django 4.1.2 on 2022-10-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0003_remove_class_student_class_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeday',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='CollegeDay_student', to='Attendance_System.student'),
        ),
    ]
