# Generated by Django 4.1.2 on 2022-10-18 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance_System', '0004_collegeday_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Class_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='collegeday',
            name='CollegeDay_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='staff_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='Semester_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('website', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
