# Generated by Django 4.1.2 on 2022-10-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0005_alter_class_class_id_alter_class_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
