# Generated by Django 4.1.2 on 2022-10-19 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0006_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField()),
                ('collegeday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance_System.collegeday')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance_System.student')),
            ],
        ),
    ]
