# Generated by Django 4.1.2 on 2022-10-19 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance_System', '0007_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeday',
            name='attendance_rate',
            field=models.ManyToManyField(blank=True, null=True, related_name='User_attendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
