# Generated by Django 3.1.7 on 2022-10-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0010_auto_20221020_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeday',
            name='CollegeDay_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance_System.lecturer'),
        ),
        migrations.AlterField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_class', to='Attendance_System.lecturer'),
        ),
        migrations.AlterField(
            model_name='collegeday',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
