# Generated by Django 3.1.7 on 2022-10-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0011_auto_20221020_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance_System.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='collegeday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance_System.collegeday'),
        ),
    ]
